workspace(name = "nl_tulipsolutions_tecl_examples_python")

local_repository(
    name = "nl_tulipsolutions_tecl",
    path = "../..",
)

load("@nl_tulipsolutions_tecl//bazel:repositories.bzl", nl_tulipsolutions_tecl_repositories = "repositories")

nl_tulipsolutions_tecl_repositories()

# Check Bazel version when invoked by Bazel directly instead of Bazelisk; verify it's at minimum the version Bazelisk
# would choose to use via .bazelversion file.
load("@nl_tulipsolutions_tecl//bazel/rules_bazel_version:deps.bzl", "bazel_version_dependencies")

bazel_version_dependencies()

load("@nl_tulipsolutions_tecl//bazel/rules_bazel_version:def.bzl", "bazel_version")

bazel_version(name = "bazel_version")

load("@bazel_version//:check.bzl", "check_bazel_version")

check_bazel_version()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@io_bazel_rules_python//python:pip.bzl", "pip_import", "pip_repositories")

pip_repositories()

pip_import(
    name = "grpc_python_dependencies",
    requirements = "@nl_tulipsolutions_tecl//python:requirements.txt",
)

load("@grpc_python_dependencies//:requirements.bzl", grpc_python_pip_install = "pip_install")

grpc_python_pip_install()

# Required because of the go_proto_library targets in the referenced proto build files
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies")

go_rules_dependencies()
