workspace(name = "nl_tulipsolutions_tecl_examples_java")

local_repository(
    name = "nl_tulipsolutions_tecl",
    path = "../..",
)

load("@nl_tulipsolutions_tecl//bazel:repositories.bzl", nl_tulipsolutions_tecl_repositories = "repositories")

nl_tulipsolutions_tecl_repositories()

# Check Bazel version when invoked by Bazel directly instead of Bazelisk; verify it's at minimum the version Bazelisk
# would choose to use via .bazelversion file.
load("@nl_tulipsolutions_tecl//bazel/rules_bazel_version:deps.bzl", "bazel_version_dependencies")

bazel_version_dependencies()

load("@nl_tulipsolutions_tecl//bazel/rules_bazel_version:def.bzl", "bazel_version")

bazel_version(name = "bazel_version")

load("@bazel_version//:check.bzl", "check_bazel_version")

check_bazel_version()

load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")

grpc_java_repositories(
    omit_com_google_protobuf = True,
)

# Required because of the go_proto_library targets in the referenced proto build files
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies")

go_rules_dependencies()
