workspace(
    name = "nl_tulipsolutions_tecl_examples_node",
    managed_directories = {"@npm": ["node_modules"]},
)

local_repository(
    name = "nl_tulipsolutions_tecl",
    path = "../..",
)

load("@nl_tulipsolutions_tecl//bazel:repositories.bzl", nl_tulipsolutions_tecl_repositories = "repositories")

nl_tulipsolutions_tecl_repositories()

# Check Bazel version when invoked by Bazel directly instead of Bazelisk; verify it's at minimum the version Bazelisk
# would choose to use via .bazelversion file.
load("@nl_tulipsolutions_tecl//bazel/rules_bazel_version:deps.bzl", "bazel_version_dependencies")

bazel_version_dependencies()

load("@nl_tulipsolutions_tecl//bazel/rules_bazel_version:def.bzl", "bazel_version")

bazel_version(name = "bazel_version")

load("@bazel_version//:check.bzl", "check_bazel_version")

check_bazel_version()

load("@build_bazel_rules_nodejs//:defs.bzl", "yarn_install")

yarn_install(
    name = "npm",
    package_json = "@nl_tulipsolutions_tecl//:package.json",
    yarn_lock = "@nl_tulipsolutions_tecl//:yarn.lock",
)
